[package]
name = "steel_example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
steel-core = "0.5.0"
steel-interpreter = "0.5.0"
