[package]
name = "gtk_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk4 = "0.8.0"
adw = { version = "0.6.0", package = "libadwaita", features = ["v1_4"] }
once_cell = "1.19.0"
