name: Build 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: [self-hosted, arch]
    name: Build and Deploy
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
    - uses: actions/checkout@v3
      with:
        path: 'resetDoc'
    - run: rm -r output
    - run: mkdir output
    - run: plantuml resetDoc/files/architecture.txt -o ~/actions-runner/_work/ReSet-Doc/ReSet-Doc/files/ -tsvg
    - run: plantuml resetDoc/files/dynamic_libraries.txt -o ~/actions-runner/_work/ReSet-Doc/ReSet-Doc/files/ -tsvg 
    - run: plantuml resetDoc/files/interpreted_languages.txt -o ~/actions-runner/_work/ReSet-Doc/ReSet-Doc/files/ -tsvg 
    - run: plantuml resetDoc/files/plugin_integration_test.txt -o ~/actions-runner/_work/ReSet-Doc/ReSet-Doc/files/ -tsvg 
    - run: typst compile ReSet.typ output/ReSet.pdf
    - uses: actions/upload-pages-artifact@v1
      with: { path: 'output' }
    - uses: actions/deploy-pages@v2
