name: Build 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: [self-hosted, arch]
    name: Build and Deploy
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
    - uses: actions/checkout@v3
      with:
        path: 'doc'
    - run: rm -r output
    - run: mkdir output
    - run: cd doc
    - run: ls
    - run: cd ..
    - run: plantuml -Djava.awt.headless=true doc/files/domain_model.txt -tsvg 
    - run: plantuml -Djava.awt.headless=true doc/files/architecture.txt -tsvg 
    - run: plantuml -Djava.awt.headless=true doc/files/wifi_architecture.txt -tsvg 
    - run: plantuml -Djava.awt.headless=true doc/files/dbus_sequence.txt -tsvg 
    - run: typst compile ReSet.typ output/ReSet.pdf
    - uses: actions/upload-pages-artifact@v1
      with: { path: 'output' }
    - uses: actions/deploy-pages@v2
