name: Build 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: [self-hosted, arch]
    name: Build and Deploy
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build images
      run: |
        plantuml files/architecture.txt -tsvg
        plantuml files/dynamic_libraries.txt -tsvg 
        plantuml files/interpreted_languages.txt -tsvg 
        plantuml files/plugin_integration_test.txt -tsvg 
        plantuml files/hourglass.txt -tsvg 
        plantuml files/global_offset_table.txt -tsvg 
    - name: Typst
      uses: lvignoli/typst-action@main
      with:
        source_file: ReSet.typ
    - name: Upload PDF file
      uses: actions/upload-pages-artifact@v1
    - name: Deploy PDF
      uses: actions/deploy-pages@v2
