name: Build 

on:
  push:
  pull:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: DeterminateSystems/nix-installer-action@main
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - run: mkdir output
    - run: nix run github:typst/typst -- compile ReSet.typ --out output/ReSet.pdf
    - uses: actions/upload-pages-artifact@v1
      with: { path: 'output' }
    - uses: actions/deploy-pages@v2
