name: Build 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: [self-hosted, arch]
    name: Build and Deploy
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
    - uses: actions/checkout@v3
    - run: mkdir output
    - run: plantuml -- files/domain_model.txt -tsvg 
    - run: plantuml -- files/architecture.txt -tsvg 
    - run: plantuml -- files/wifi_architecture.txt -tsvg 
    - run: plantuml -- files/dbus_sequence.txt -tsvg 
    - run: github:typst/typst -- compile ReSet.typ output/ReSet.pdf
    - uses: actions/upload-pages-artifact@v1
      with: { path: 'output' }
    - uses: actions/deploy-pages@v2
