name: Build 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: [self-hosted, arch]
    name: Build and Deploy
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build images
      run: |
        plantuml files/architecture.txt -tsvg
        plantuml files/dynamic_libraries.txt -tsvg 
        plantuml files/interpreted_languages.txt -tsvg 
        plantuml files/plugin_integration_test.txt -tsvg 
        plantuml files/hourglass.txt -tsvg 
        plantuml files/global_offset_table.txt -tsvg
        plantuml files/mock_implementation.txt -tsvg
        plantuml files/wayland_architecture.txt -tsvg
    - name: Build PDF
      run: |
        mkdir output
        typst compile ReSet.typ output/ReSet.pdf
    - name: Upload PDF file
      uses: actions/upload-pages-artifact@v3
      with: { path: 'output' }
    - name: Deploy PDF
      uses: actions/deploy-pages@v4
